import { Modal, Input } from 'antd'
import { Icon } from '@iconify/react'
import { useState } from 'react'
import { toast } from 'react-hot-toast'

type PaymentMethodModalProps = {
  visible: boolean
  onCancel: () => void
  onSelectPaymentMethod: (
    method: 'POS' | 'CASH' | 'Online Payment',
    posReceiptNo?: string,
    posType?: 'internal' | 'external'
  ) => void
  setPosReceiptNo: React.Dispatch<React.SetStateAction<string>>
  posReceiptNo: string
}

const PaymentMethodModal = ({
  visible,
  onCancel,
  onSelectPaymentMethod,
  setPosReceiptNo,
  posReceiptNo,
}: PaymentMethodModalProps) => {
  const [selectedMethod, setSelectedMethod] = useState<
    'POS (Internal)' | 'POS (External)' | 'CASH' | 'Online Payment' | null
  >(null)
  const [showPosInput, setShowPosInput] = useState(false)

  const handleSelectPaymentMethod = (
    method: 'POS (Internal)' | 'POS (External)' | 'CASH' | 'Online Payment'
  ) => {
    setSelectedMethod(method)

    if (method === 'POS (Internal)' || method === 'POS (External)') {
      setShowPosInput(true)
    } else if (method === 'CASH') {
      // Auto-generate transaction ID for CASH
      const autoGeneratedTransactionId = `CASH-${Date.now()}`
      onSelectPaymentMethod('CASH', autoGeneratedTransactionId, 'internal')
    } else {
      onSelectPaymentMethod('Online Payment', 'internal')
    }
  }

  const handleSubmitPosReceipt = () => {
    if (!posReceiptNo.trim()) {
      toast.error('POS Receipt Number cannot be empty')
      return
    }

    if (posReceiptNo.trim().length < 8) {
      toast.error('The transaction ID must be at least 8 characters')
      return
    }

    // Determine posType based on selected method
    const posType =
      selectedMethod === 'POS (Internal)' ? 'internal' : 'external'

    onSelectPaymentMethod('POS', posReceiptNo, posType)

    // Reset states
    setPosReceiptNo('')
    setShowPosInput(false)
    setSelectedMethod(null)
  }

  const handleCancel = () => {
    // Reset states
    setPosReceiptNo('')
    setShowPosInput(false)
    setSelectedMethod(null)
    onCancel()
  }

  return (
    <Modal
      title="Select Payment Method"
      open={visible}
      onCancel={handleCancel}
      footer={null}
    >
      {!showPosInput ? (
        <div className="flex flex-col gap-4">
          <button
            className="flex items-center justify-between p-4 border rounded"
            onClick={() => handleSelectPaymentMethod('POS (Internal)')}
          >
            <span>POS (Internal)</span>
            <Icon icon="mdi:credit-card" width="24" height="24" />
          </button>
          <button
            className="flex items-center justify-between p-4 border rounded"
            onClick={() => handleSelectPaymentMethod('POS (External)')}
          >
            <span>POS (External)</span>
            <Icon icon="mdi:credit-card" width="24" height="24" />
          </button>
          <button
            className="flex items-center justify-between p-4 border rounded"
            onClick={() => handleSelectPaymentMethod('CASH')}
          >
            <span>CASH</span>
            <Icon icon="mdi:cash" width="24" height="24" />
          </button>
          <button
            className="flex items-center justify-between p-4 border rounded"
            onClick={() => handleSelectPaymentMethod('Online Payment')}
          >
            <span>Online Payment</span>
            <Icon icon="mdi:bank-transfer" width="24" height="24" />
          </button>
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          <div className="mb-2">
            <label
              htmlFor="posReceiptNo"
              className="block text-sm font-medium text-gray-700 mb-1"
            >
              Enter POS Receipt Number:
            </label>
            <Input
              id="posReceiptNo"
              value={posReceiptNo}
              onChange={(e) => setPosReceiptNo(e.target.value)}
              placeholder="e.g., POS12345678"
              className="w-full"
            />
          </div>
          <div className="flex justify-end gap-2 mt-2">
            <button
              className="border border-gray-300 rounded px-4 py-2"
              onClick={() => setShowPosInput(false)}
            >
              Back
            </button>
            <button
              className="bg-[#4880FF] text-white rounded px-4 py-2"
              onClick={handleSubmitPosReceipt}
              disabled={!posReceiptNo.trim()}
            >
              Proceed
            </button>
          </div>
        </div>
      )}
    </Modal>
  )
}

export default PaymentMethodModal
